twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        appName: "CentralProjet"
        appYear: "2025"

when@test:
    twig:
        strict_variables: true
